### ISSUE TITLE
Rarefaction curves

### ISSUE THREAD

**Issue by mtisza1** [UriNeri/RVMT#1]
Hi Uri,

Congrats on a very interesting project. I would like to regenerate the rarefaction plots from Figure 1 of the current Biorxiv paper. Are you able to provide the input table and code for making these plots? Apologies in advance if these were already posted somewhere.

Best,

Mike

**Comment by UriNeri** [comment]
Hi @mtisza1! thanks for the kind words!   
@simroux uploaded a [folder](https://github.com/UriNeri/RVMT/tree/main/Rarefaction_curves) with R code to recreate the plots and and example input data.  Simon would know better than me, but the input data is "example" as it was generated by performing the bootstraping via repeated list permutation of the different metatranscriptomic info for the different sample sizes. So I suppose running a new bootstrapping for each sample size could get you slightly different numeric values,  but from what we seen the over all trend (and general "look") would be the same. btw we also got very similarly looking plots with repeated down-subsampling instead of list-permutations, and we'd be happy to share that code too if you want :)  
HTH

**Comment by mtisza1** [comment]
Thank you, Uri and Simon. I was able to recreate your plots without issue.

@simroux I was able to put my own "rarefaction matrices" into the R package "micropan" rarefaction module with multiple permutations, then I could parse the tables to get mean, minimum, and maximum for the these values. Did you use a similar approach?

Best,

Mike

**Comment by simroux** [comment]
Hi Mike,

Yes, pretty much, except I did that with custom Perl scripts :-) But yes, looking at micropan, it seems to do the same thing.

Best,
Simon

**Comment by mtisza1** [comment]
Great, thanks!
